config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root to: "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true

  after_create_commit { broadcast_prepend_to "tweets" }
  after_destroy_commit { broadcast_remove_to "tweets" }
  after_update_commit { broadcast_replace_to "tweets" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order(created_at: :desc)
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        # route turbo validation errors
        format.turbo_stream # populate `create.turbo_stream.erb`
        # this is better if if create.turbo_stream.erb in happy path also needs a @tweet replace
        # format.turbo_stream {render turbo_stream: turbo_stream.replace(
        #                             # @tweet, partial: "tweets/modal_form",
        #                             "new_tweet", partial: "tweets/modal_form",
        #                             locals: { tweet: @tweet}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Tweets</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <%= yield :head %>
  <%= turbo_include_tags %>
</head>

<body>
  <p id="notice"><%= notice %></p>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>

</html>

app/views/shared/_flash.html.erb
<div id="flash">
  <p id="notice"><%= notice %></p>
</div>

app/views/shared/_notice.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "shared/toast", locals: {notice: notice} %>

app/views/shared/_toast.html.erb
<div data-controller="toast" data-delay="2000" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <img src="..." class="rounded mr-2" alt="...">
    <strong class="mr-auto">Success!</strong>
    <small class="text-muted">hi</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body">
    <%= notice %>
  </div>
</div>

app/views/tweets/_edit_modal.html.erb
<%= link_to "#", class: 'btn btn-sm btn-outline-primary', data: { toggle: "modal", target: "#editTweetModal" } do %>
  Edit Tweet
<% end %>

<div class="modal fade" id="editTweetModal" tabindex="-1" aria-labelledby="exampleEditModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <%= render "tweets/modal_form", tweet: tweet %>

    </div>
  </div>
</div>

app/views/tweets/_form.html.erb
<%# form_with(model: tweet, id: dom_id(tweet)) do |form| %>
<%= form_with(model: tweet, id: dom_id(tweet),
              data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}
            ) do |form| %>
<% if tweet.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

  <ul>
    <% tweet.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :body %>
  <%= form.text_area :body %>
</div>

<div class="actions">
  <%= form.submit class: "btn btn-sm btn-outline-success" %>
  <%= link_to "Cancel", @tweet, class: "btn btn-sm btn-outline-danger" %>
</div>
<% end %>

app/views/tweets/_modal.html.erb
<%= link_to "#", class: 'btn btn-sm btn-outline-primary', data: { toggle: "modal", target: "#tweetModal" } do %>
  New Tweet
<% end %>

<div class="modal fade" id="tweetModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>

        <div class="modal-header">
          <h5 class="modal-title">New Tweet</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <% if tweet.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

            <ul>
              <% tweet.errors.each do |error| %>
              <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>

          <div class="field">
            <%= form.label :body %>
            <%= form.text_area :body %>
          </div>
        </div>

        <div class="modal-footer">
          <div class="actions">
            <%= form.submit class: "btn btn-sm btn-outline-success" %>
            <%= link_to "Cancel", tweet, class: "btn btn-sm btn-outline-danger" %>
          </div>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/tweets/_modal_form.html.erb
<%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>

  <div class="modal-header">
    <h5 class="modal-title">New Tweet</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </div>

  <div class="modal-footer">
    <div class="actions">
      <%= form.submit class: "btn btn-sm btn-outline-success" %>
      <%= link_to "Cancel", tweet, class: "btn btn-sm btn-outline-danger" %>
    </div>
  </div>

<% end %>

app/views/tweets/_new_modal.html.erb
<%= link_to "#", class: 'btn btn-sm btn-outline-primary', data: { toggle: "modal", target: "#tweetModal" } do %>
  New Tweet
<% end %>

<div class="modal fade" id="tweetModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <%= render "tweets/modal_form", tweet: tweet %>

    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
  <div class="card card-body">
    <div><%= tweet.body %></div>
    <%= render "tweets/tweet_actions", tweet: tweet %>
  </div>
<% end %>

app/views/tweets/_tweet_actions.html.erb
<div class="btn-toolbar mt-4" role="toolbar">
  <div class="btn-group mr-2" role="group">
    <%= render "tweets/edit_modal", tweet: tweet %>
    <%= link_to 'Edit', edit_tweet_path(tweet),
                class: "btn btn-sm btn-outline-primary" %>
    <%= link_to 'Destroy', tweet_path(tweet), method: :delete,
                data: { confirm: 'Are you sure?' },
                class: "btn btn-sm btn-outline-danger" %>
  </div>
</div>

app/views/tweets/create.turbo_stream.erb
<!-- to prepend on create - disabled to avoid double vision when broadcasting -->
<%#%   stream_action   dom_id_target, render_partial,       send_local_variables   %>
<%# turbo_stream.prepend "tweets", partial: "tweets/tweet", locals: { tweet: @tweet } %>

<%# clear form on create - without js %>
<%# turbo_stream.replace "tweet-form", partial: "tweets/form", locals: { tweet: Tweet.new } %>

<%# to send a message to the notice partial %>
<%= turbo_stream.append "notice", partial: "shared/notice", locals: {notice: "Tweet created."} %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render 'form', tweet: @tweet %>
<% end %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/edit.turbo_stream.erb
<%# turbo_stream.replace "new_tweet", partial: "tweets/modal_form", locals: { tweet: @tweet } %>
<!--              dom_id_target, render_partial,               send_local_variables    -->
<%= turbo_stream.replace @tweet, partial: "tweets/edit_modal", locals: { tweet: @tweet } %>

app/views/tweets/index-edit_modal.html.erb
<h1>Tweets</h1>
<%= turbo_stream_from "tweets" %>

<%= render "tweets/new_modal", tweet: @tweet %>

<h2 class="mt-3 h4 text-muted">Tweet Feed</h2>
<%= turbo_frame_tag "tweets" do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>
<%= turbo_stream_from "tweets" %>

<h2 class="mt-3 h4 text-muted">New Tweet</h2>
<%= render "tweets/modal_new", tweet: @tweet %>

<!--
<div class="card card-body">
  <%= turbo_frame_tag "tweet-form" do %>
    <%= render "tweets/form", tweet: @tweet %>
  <% end %>
</div>
-->

<h2 class="mt-3 h4 text-muted">Tweet Feed</h2>
<%= turbo_frame_tag "tweets" do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= turbo_frame_tag "new-tweet", target: "_top" do %>
  <%= render 'form', tweet: @tweet %>
<% end %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render @tweet %>
<% end %>
<%= link_to 'Back', tweets_path %>